2020-08-28 19:10:56,257:app:ERROR:Exception on /search [GET]
Traceback (most recent call last):
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\program files\python38\lib\site-packages\flask_apispec\annotations.py", line 118, in wrapped
    return wrapper(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_apispec\wrapper.py", line 33, in __call__
    response = self.call_view(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_apispec\wrapper.py", line 56, in call_view
    return self.func(*args, **kwargs)
  File "C:\localhost\GitHub\feruc\RaillWayTickets\server-side\app\routes\main\views.py", line 39, in get_schedules
    routes = get_fit_routes(routes_info)
  File "C:\localhost\GitHub\feruc\RaillWayTickets\server-side\app\routes\main\views.py", line 49, in get_fit_routes
    for i in range(len(routes_info)):
TypeError: object of type 'Query' has no len()
2020-08-28 19:12:43,854:app:ERROR:Exception on /search [GET]
Traceback (most recent call last):
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\program files\python38\lib\site-packages\flask_apispec\annotations.py", line 118, in wrapped
    return wrapper(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_apispec\wrapper.py", line 37, in __call__
    mv = self.marshal_result(rv, status_code)
  File "c:\program files\python38\lib\site-packages\flask_apispec\wrapper.py", line 66, in marshal_result
    dumped = schema.dump(result)
  File "c:\program files\python38\lib\site-packages\marshmallow\schema.py", line 557, in dump
    result = self._serialize(processed_obj, many=many)
  File "c:\program files\python38\lib\site-packages\marshmallow\schema.py", line 521, in _serialize
    value = field_obj.serialize(attr_name, obj, accessor=self.get_attribute)
  File "c:\program files\python38\lib\site-packages\marshmallow\fields.py", line 312, in serialize
    return self._serialize(value, attr, obj, **kwargs)
  File "c:\program files\python38\lib\site-packages\marshmallow\fields.py", line 700, in _serialize
    return [self.inner._serialize(each, attr, obj, **kwargs) for each in value]
  File "c:\program files\python38\lib\site-packages\marshmallow\fields.py", line 700, in <listcomp>
    return [self.inner._serialize(each, attr, obj, **kwargs) for each in value]
  File "c:\program files\python38\lib\site-packages\marshmallow\fields.py", line 567, in _serialize
    return schema.dump(nested_obj, many=many)
  File "c:\program files\python38\lib\site-packages\marshmallow\schema.py", line 557, in dump
    result = self._serialize(processed_obj, many=many)
  File "c:\program files\python38\lib\site-packages\marshmallow\schema.py", line 521, in _serialize
    value = field_obj.serialize(attr_name, obj, accessor=self.get_attribute)
  File "c:\program files\python38\lib\site-packages\marshmallow\fields.py", line 312, in serialize
    return self._serialize(value, attr, obj, **kwargs)
  File "c:\program files\python38\lib\site-packages\marshmallow\fields.py", line 1201, in _serialize
    return format_func(value)
  File "c:\program files\python38\lib\site-packages\marshmallow\utils.py", line 192, in isoformat
    return datetime.isoformat()
AttributeError: 'str' object has no attribute 'isoformat'
2020-09-05 21:30:04,433:app:WARNING:user:1 - failed to read profile: 'Query' object is not callable
2020-09-05 21:30:38,697:app:WARNING:user:1 - failed to read profile: 'Query' object is not callable
2020-09-05 21:31:27,206:app:WARNING:user:1 - failed to read profile: filter() got an unexpected keyword argument 'user_id'
2020-09-05 21:32:34,024:app:ERROR:Exception on /user_tickets [GET]
Traceback (most recent call last):
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_jwt_extended\view_decorators.py", line 108, in wrapper
    return fn(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_apispec\annotations.py", line 118, in wrapped
    return wrapper(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_apispec\wrapper.py", line 33, in __call__
    response = self.call_view(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_apispec\wrapper.py", line 56, in call_view
    return self.func(*args, **kwargs)
  File "C:\localhost\GitHub\feruc\RaillWayTickets\server-side\app\routes\profile\views.py", line 46, in get
    return UserInfoView.prepare_to_serialize(tickets)
AttributeError: type object 'UserInfoView' has no attribute 'prepare_to_serialize'
2020-09-05 21:38:09,616:app:ERROR:Exception on /user_tickets [GET]
Traceback (most recent call last):
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_jwt_extended\view_decorators.py", line 108, in wrapper
    return fn(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_apispec\annotations.py", line 118, in wrapped
    return wrapper(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_apispec\wrapper.py", line 33, in __call__
    response = self.call_view(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_apispec\wrapper.py", line 56, in call_view
    return self.func(*args, **kwargs)
  File "C:\localhost\GitHub\feruc\RaillWayTickets\server-side\app\routes\profile\views.py", line 46, in get
    return UsersTickets.prepare_to_serialize(tickets)
  File "C:\localhost\GitHub\feruc\RaillWayTickets\server-side\app\routes\profile\views.py", line 68, in prepare_to_serialize
    'arrival_time': arr_station_stop.arrival,
AttributeError: 'Stop' object has no attribute 'arrival'
2020-09-07 23:56:47,890:app:ERROR:Exception on /user_tickets [GET]
Traceback (most recent call last):
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_jwt_extended\view_decorators.py", line 108, in wrapper
    return fn(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_apispec\annotations.py", line 118, in wrapped
    return wrapper(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_apispec\wrapper.py", line 33, in __call__
    response = self.call_view(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_apispec\wrapper.py", line 56, in call_view
    return self.func(*args, **kwargs)
  File "C:\localhost\GitHub\feruc\RaillWayTickets\server-side\app\routes\profile\views.py", line 46, in get
    return UsersTickets.prepare_to_serialize(tickets)
  File "C:\localhost\GitHub\feruc\RaillWayTickets\server-side\app\routes\profile\views.py", line 61, in prepare_to_serialize
    dep_station = Station.query.get(dep_station_stop.station_id)
AttributeError: 'NoneType' object has no attribute 'station_id'
2020-09-07 23:59:25,179:app:ERROR:Exception on /user_tickets [GET]
Traceback (most recent call last):
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_jwt_extended\view_decorators.py", line 108, in wrapper
    return fn(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_apispec\annotations.py", line 118, in wrapped
    return wrapper(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_apispec\wrapper.py", line 33, in __call__
    response = self.call_view(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_apispec\wrapper.py", line 56, in call_view
    return self.func(*args, **kwargs)
  File "C:\localhost\GitHub\feruc\RaillWayTickets\server-side\app\routes\profile\views.py", line 46, in get
    return UsersTickets.prepare_to_serialize(tickets)
  File "C:\localhost\GitHub\feruc\RaillWayTickets\server-side\app\routes\profile\views.py", line 61, in prepare_to_serialize
    dep_station = Station.query.get(dep_station_stop.station_id)
AttributeError: 'NoneType' object has no attribute 'station_id'
2020-09-08 00:57:50,144:app:ERROR:Exception on /book_ticket [POST]
Traceback (most recent call last):
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\program files\python38\lib\site-packages\flask_jwt_extended\view_decorators.py", line 108, in wrapper
    return fn(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_apispec\annotations.py", line 118, in wrapped
    return wrapper(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_apispec\wrapper.py", line 33, in __call__
    response = self.call_view(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_apispec\wrapper.py", line 56, in call_view
    return self.func(*args, **kwargs)
  File "C:\localhost\GitHub\feruc\RaillWayTickets\server-side\app\routes\main\views.py", line 76, in book_ticket
    train_dep_time = session.query(Schedule.departure_time).get(kwargs.get('schedule_id'))
  File "c:\program files\python38\lib\site-packages\sqlalchemy\orm\query.py", line 1021, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
  File "c:\program files\python38\lib\site-packages\sqlalchemy\orm\query.py", line 1082, in _get_impl
    mapper = self._only_full_mapper_zero("get")
  File "c:\program files\python38\lib\site-packages\sqlalchemy\orm\query.py", line 437, in _only_full_mapper_zero
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: get() can only be used against a single mapped class.
2020-09-08 01:01:20,213:app:ERROR:Exception on /book_ticket [POST]
Traceback (most recent call last):
  File "c:\program files\python38\lib\site-packages\sqlalchemy\engine\base.py", line 1277, in _execute_context
    self.dialect.do_execute(
  File "c:\program files\python38\lib\site-packages\sqlalchemy\engine\default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: NOT NULL constraint failed: tickets.place_num

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\program files\python38\lib\site-packages\flask_jwt_extended\view_decorators.py", line 108, in wrapper
    return fn(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_apispec\annotations.py", line 118, in wrapped
    return wrapper(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_apispec\wrapper.py", line 33, in __call__
    response = self.call_view(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_apispec\wrapper.py", line 56, in call_view
    return self.func(*args, **kwargs)
  File "C:\localhost\GitHub\feruc\RaillWayTickets\server-side\app\routes\main\views.py", line 87, in book_ticket
    session.commit()
  File "c:\program files\python38\lib\site-packages\sqlalchemy\orm\scoping.py", line 163, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\sqlalchemy\orm\session.py", line 1042, in commit
    self.transaction.commit()
  File "c:\program files\python38\lib\site-packages\sqlalchemy\orm\session.py", line 504, in commit
    self._prepare_impl()
  File "c:\program files\python38\lib\site-packages\sqlalchemy\orm\session.py", line 483, in _prepare_impl
    self.session.flush()
  File "c:\program files\python38\lib\site-packages\sqlalchemy\orm\session.py", line 2523, in flush
    self._flush(objects)
  File "c:\program files\python38\lib\site-packages\sqlalchemy\orm\session.py", line 2664, in _flush
    transaction.rollback(_capture_exception=True)
  File "c:\program files\python38\lib\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "c:\program files\python38\lib\site-packages\sqlalchemy\util\compat.py", line 178, in raise_
    raise exception
  File "c:\program files\python38\lib\site-packages\sqlalchemy\orm\session.py", line 2624, in _flush
    flush_context.execute()
  File "c:\program files\python38\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 422, in execute
    rec.execute(self)
  File "c:\program files\python38\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 586, in execute
    persistence.save_obj(
  File "c:\program files\python38\lib\site-packages\sqlalchemy\orm\persistence.py", line 239, in save_obj
    _emit_insert_statements(
  File "c:\program files\python38\lib\site-packages\sqlalchemy\orm\persistence.py", line 1135, in _emit_insert_statements
    result = cached_connections[connection].execute(
  File "c:\program files\python38\lib\site-packages\sqlalchemy\engine\base.py", line 1014, in execute
    return meth(self, multiparams, params)
  File "c:\program files\python38\lib\site-packages\sqlalchemy\sql\elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "c:\program files\python38\lib\site-packages\sqlalchemy\engine\base.py", line 1127, in _execute_clauseelement
    ret = self._execute_context(
  File "c:\program files\python38\lib\site-packages\sqlalchemy\engine\base.py", line 1317, in _execute_context
    self._handle_dbapi_exception(
  File "c:\program files\python38\lib\site-packages\sqlalchemy\engine\base.py", line 1511, in _handle_dbapi_exception
    util.raise_(
  File "c:\program files\python38\lib\site-packages\sqlalchemy\util\compat.py", line 178, in raise_
    raise exception
  File "c:\program files\python38\lib\site-packages\sqlalchemy\engine\base.py", line 1277, in _execute_context
    self.dialect.do_execute(
  File "c:\program files\python38\lib\site-packages\sqlalchemy\engine\default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) NOT NULL constraint failed: tickets.place_num
[SQL: INSERT INTO tickets (user_id, departure_stop, arrival_stop, cost, wagon_id, place_num, schedule_id, is_booked, book_end_date) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: (1, 1, 4, 34, 1, None, 1, 1, '2020-09-27 00:00:00.000000')]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2020-09-09 23:55:26,428:app:ERROR:Exception on /delete_ticket [POST]
Traceback (most recent call last):
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\program files\python38\lib\site-packages\flask_jwt_extended\view_decorators.py", line 108, in wrapper
    return fn(*args, **kwargs)
  File "C:\localhost\GitHub\feruc\RaillWayTickets\server-side\app\decorators.py", line 13, in decorated_f
    return make_response(401)
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\helpers.py", line 223, in make_response
    return current_app.make_response(args)
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 2127, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a int.
2020-09-10 00:01:52,638:app:INFO:manager 2 deleted ticket
2020-09-10 00:02:48,046:app:INFO:manager 2 deleted ticket
2020-09-10 00:23:17,810:app:INFO:manager 2 deleted ticket
2020-09-10 00:23:22,909:app:ERROR:Exception on /search_tickets [POST]
Traceback (most recent call last):
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\program files\python38\lib\site-packages\flask_jwt_extended\view_decorators.py", line 108, in wrapper
    return fn(*args, **kwargs)
  File "C:\localhost\GitHub\feruc\RaillWayTickets\server-side\app\decorators.py", line 14, in decorated_f
    return f(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_apispec\annotations.py", line 118, in wrapped
    return wrapper(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_apispec\wrapper.py", line 33, in __call__
    response = self.call_view(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_apispec\wrapper.py", line 56, in call_view
    return self.func(*args, **kwargs)
  File "C:\localhost\GitHub\feruc\RaillWayTickets\server-side\app\routes\profile\views.py", line 85, in search_tickets
    return make_response(400)
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\helpers.py", line 223, in make_response
    return current_app.make_response(args)
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 2127, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a int.
2020-09-10 00:26:03,520:app:INFO:manager 2 deleted ticket
2020-09-10 00:26:08,790:app:INFO:manager 2  accessed tickets list
2020-09-10 00:26:08,830:app:ERROR:Exception on /search_tickets [POST]
Traceback (most recent call last):
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\program files\python38\lib\site-packages\flask_jwt_extended\view_decorators.py", line 108, in wrapper
    return fn(*args, **kwargs)
  File "C:\localhost\GitHub\feruc\RaillWayTickets\server-side\app\decorators.py", line 14, in decorated_f
    return f(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_apispec\annotations.py", line 118, in wrapped
    return wrapper(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_apispec\wrapper.py", line 33, in __call__
    response = self.call_view(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_apispec\wrapper.py", line 56, in call_view
    return self.func(*args, **kwargs)
  File "C:\localhost\GitHub\feruc\RaillWayTickets\server-side\app\routes\profile\views.py", line 83, in search_tickets
    tickets = get_tickets(**kwargs)
  File "C:\localhost\GitHub\feruc\RaillWayTickets\server-side\app\routes\profile\views.py", line 141, in get_tickets
    return session.query(Ticket).get(kwargs.get('ticket_id')).all()
AttributeError: 'Ticket' object has no attribute 'all'
2020-09-10 00:26:58,490:app:INFO:manager 2 deleted ticket
2020-09-10 00:27:03,405:app:INFO:manager 2  accessed tickets list
2020-09-10 00:27:03,440:app:INFO:manager 2  accessed tickets list
2020-09-10 00:27:03,440:app:ERROR:Exception on /search_tickets [POST]
Traceback (most recent call last):
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\program files\python38\lib\site-packages\flask_jwt_extended\view_decorators.py", line 108, in wrapper
    return fn(*args, **kwargs)
  File "C:\localhost\GitHub\feruc\RaillWayTickets\server-side\app\decorators.py", line 14, in decorated_f
    return f(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_apispec\annotations.py", line 118, in wrapped
    return wrapper(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_apispec\wrapper.py", line 33, in __call__
    response = self.call_view(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_apispec\wrapper.py", line 56, in call_view
    return self.func(*args, **kwargs)
  File "C:\localhost\GitHub\feruc\RaillWayTickets\server-side\app\routes\profile\views.py", line 85, in search_tickets
    return UsersTickets.prepare_to_serialize(tickets)
  File "C:\localhost\GitHub\feruc\RaillWayTickets\server-side\app\routes\profile\views.py", line 52, in prepare_to_serialize
    for ticket in tickets:
TypeError: 'Ticket' object is not iterable
2020-09-10 00:27:28,930:app:INFO:manager 2 deleted ticket
2020-09-10 00:27:34,525:app:INFO:manager 2  accessed tickets list
2020-09-10 00:27:34,565:app:INFO:manager 2  accessed tickets list
2020-09-10 00:29:55,970:app:INFO:manager 2 deleted ticket
2020-09-10 00:30:03,570:app:INFO:manager 2  accessed tickets list
2020-09-10 00:30:03,665:app:INFO:manager 2  accessed tickets list
2020-09-10 00:31:10,192:app:INFO:manager 2 deleted ticket
2020-09-10 00:31:15,798:app:INFO:manager 2  accessed tickets list
2020-09-10 00:31:15,833:app:INFO:manager 2  accessed tickets list
2020-09-10 22:50:52,417:app:INFO:manager 2 deleted ticket
2020-09-10 22:50:57,986:app:INFO:manager 2  accessed tickets list
2020-09-10 22:50:58,026:app:INFO:manager 2  accessed tickets list
2020-09-10 22:52:47,212:app:INFO:manager 2 deleted ticket
2020-09-10 22:52:54,346:app:INFO:manager 2  accessed tickets list
2020-09-10 22:52:54,376:app:INFO:manager 2  accessed tickets list
2020-09-10 22:54:18,926:app:INFO:manager 2 deleted ticket
2020-09-10 22:54:23,576:app:INFO:manager 2  accessed tickets list
2020-09-10 22:54:23,601:app:INFO:manager 2  accessed tickets list
2020-09-10 23:12:15,658:app:INFO:manager 2  accessed tickets list
2020-09-10 23:12:21,728:app:INFO:manager 2 deleted ticket
2020-09-10 23:12:27,363:app:INFO:manager 2  accessed tickets list
2020-09-10 23:12:27,398:app:INFO:manager 2  accessed tickets list
2020-09-10 23:25:53,688:app:INFO:manager 2  accessed tickets list
2020-09-10 23:25:59,988:app:INFO:manager 2 deleted ticket
2020-09-10 23:26:05,459:app:INFO:manager 2  accessed tickets list
2020-09-10 23:26:05,479:app:INFO:manager 2  accessed tickets list
2020-09-10 23:30:09,626:app:INFO:manager 2  accessed tickets list
2020-09-10 23:30:15,507:app:INFO:manager 2 deleted ticket
2020-09-10 23:30:19,976:app:INFO:manager 2  accessed tickets list
2020-09-10 23:30:20,007:app:INFO:manager 2  accessed tickets list
2020-09-10 23:31:21,576:app:INFO:manager 2  accessed tickets list
2020-09-10 23:31:27,456:app:INFO:manager 2 deleted ticket
2020-09-10 23:31:32,771:app:INFO:manager 2  accessed tickets list
2020-09-10 23:31:32,806:app:INFO:manager 2  accessed tickets list
2020-09-10 23:37:41,576:app:INFO:manager 2  accessed tickets list
2020-09-10 23:37:47,965:app:INFO:manager 2 deleted ticket
2020-09-10 23:37:53,751:app:INFO:manager 2  accessed tickets list
2020-09-10 23:37:53,775:app:INFO:manager 2  accessed tickets list
2020-09-10 23:39:35,316:app:INFO:manager 2  accessed tickets list
2020-09-10 23:39:35,355:app:WARNING:manager: 2 - failed to verify ticket: Entity '<class 'app.model.Ticket'>' has no property 'booking_end_date'
2020-09-10 23:39:41,400:app:INFO:manager 2 deleted ticket
2020-09-10 23:39:46,944:app:INFO:manager 2  accessed tickets list
2020-09-10 23:39:46,971:app:INFO:manager 2  accessed tickets list
2020-09-10 23:41:55,332:app:INFO:manager 2  accessed tickets list
2020-09-10 23:41:55,380:app:INFO:manager 2 verified ticket 4
2020-09-10 23:41:55,386:app:INFO:manager 2  accessed tickets list
2020-09-10 23:42:01,995:app:INFO:manager 2 deleted ticket
2020-09-10 23:42:08,475:app:INFO:manager 2  accessed tickets list
2020-09-10 23:42:08,525:app:INFO:manager 2  accessed tickets list
2020-09-10 23:42:56,594:app:INFO:manager 2  accessed tickets list
2020-09-10 23:42:56,639:app:INFO:manager 2 verified ticket 4
2020-09-10 23:42:56,644:app:INFO:manager 2  accessed tickets list
2020-09-10 23:43:03,439:app:INFO:manager 2 deleted ticket
2020-09-10 23:43:19,089:app:INFO:manager 2  accessed tickets list
2020-09-10 23:43:19,129:app:INFO:manager 2 verified ticket 4
2020-09-10 23:43:19,144:app:INFO:manager 2  accessed tickets list
2020-09-10 23:43:24,629:app:INFO:manager 2 deleted ticket
2020-09-10 23:43:29,589:app:INFO:manager 2  accessed tickets list
2020-09-10 23:43:29,629:app:INFO:manager 2  accessed tickets list
2020-09-11 00:24:36,086:app:INFO:manager 2  accessed tickets list
2020-09-11 00:24:36,124:app:INFO:manager 2 verified ticket 4
2020-09-11 00:24:36,124:app:INFO:manager 2  accessed tickets list
2020-09-11 00:24:40,167:app:INFO:manager 2  accessed tickets list
2020-09-11 00:24:46,774:app:INFO:manager 2 deleted ticket
2020-09-11 00:24:52,104:app:INFO:manager 2  accessed tickets list
2020-09-11 00:24:52,142:app:INFO:manager 2  accessed tickets list
2020-09-11 00:26:12,612:app:INFO:manager 2  accessed tickets list
2020-09-11 00:26:12,659:app:INFO:manager 2 verified ticket 4
2020-09-11 00:26:12,675:app:INFO:manager 2  accessed tickets list
2020-09-11 00:26:16,840:app:INFO:manager 2  accessed tickets list
2020-09-11 00:26:18,333:app:INFO:manager 2  accessed tickets list
2020-09-11 00:26:18,370:app:INFO:manager 2  accessed tickets list
2020-09-11 00:26:23,694:app:INFO:manager 2 deleted ticket
2020-09-11 00:26:29,896:app:INFO:manager 2  accessed tickets list
2020-09-11 00:26:29,927:app:INFO:manager 2  accessed tickets list
2020-09-11 15:30:50,066:app:INFO:manager 2  accessed tickets list
2020-09-11 15:30:50,106:app:INFO:manager 2 verified ticket 4
2020-09-11 15:30:50,121:app:INFO:manager 2  accessed tickets list
2020-09-11 15:30:54,766:app:INFO:manager 2  accessed tickets list
2020-09-11 15:30:55,966:app:INFO:manager 2  accessed tickets list
2020-09-11 15:30:55,996:app:INFO:manager 2  accessed tickets list
2020-09-11 15:31:01,186:app:WARNING:user: 1 - failed to delete ticket: unsupported operand type(s) for &: 'bool' and 'str'
2020-09-11 15:31:08,006:app:INFO:manager 2  accessed tickets list
2020-09-11 15:31:08,046:app:INFO:manager 2  accessed tickets list
2020-09-11 15:49:15,847:app:INFO:manager 2  accessed tickets list
2020-09-11 15:49:15,878:app:INFO:manager 2 verified ticket 4
2020-09-11 15:49:15,894:app:INFO:manager 2  accessed tickets list
2020-09-11 15:49:20,337:app:INFO:manager 2  accessed tickets list
2020-09-11 15:49:30,320:app:WARNING:user: 1 - failed to delete ticket: unsupported operand type(s) for &: 'bool' and 'str'
2020-09-11 15:49:36,453:app:INFO:manager 2  accessed tickets list
2020-09-11 15:49:36,506:app:INFO:manager 2  accessed tickets list
2020-09-11 15:52:18,176:app:INFO:manager 2  accessed tickets list
2020-09-11 15:52:18,216:app:INFO:manager 2 verified ticket 4
2020-09-11 15:52:18,226:app:INFO:manager 2  accessed tickets list
2020-09-11 15:52:22,456:app:INFO:manager 2  accessed tickets list
2020-09-11 15:52:23,615:app:ERROR:Exception on /place_ticket [POST]
Traceback (most recent call last):
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\program files\python38\lib\site-packages\flask_jwt_extended\view_decorators.py", line 108, in wrapper
    return fn(*args, **kwargs)
  File "C:\localhost\GitHub\feruc\RaillWayTickets\server-side\app\decorators.py", line 14, in decorated_f
    return f(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_apispec\annotations.py", line 118, in wrapped
    return wrapper(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_apispec\wrapper.py", line 33, in __call__
    response = self.call_view(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_apispec\wrapper.py", line 56, in call_view
    return self.func(*args, **kwargs)
  File "C:\localhost\GitHub\feruc\RaillWayTickets\server-side\app\routes\main\views.py", line 110, in place_ticket
    user = session.query(User).filter(kwargs.get('buyer_email')).one_or_none()
  File "<string>", line 2, in filter
  File "c:\program files\python38\lib\site-packages\sqlalchemy\orm\base.py", line 227, in generate
    fn(self, *args[1:], **kw)
  File "c:\program files\python38\lib\site-packages\sqlalchemy\orm\query.py", line 1859, in filter
    criterion = expression._expression_literal_as_text(criterion)
  File "c:\program files\python38\lib\site-packages\sqlalchemy\sql\elements.py", line 4685, in _expression_literal_as_text
    return _literal_as_text(element)
  File "c:\program files\python38\lib\site-packages\sqlalchemy\sql\elements.py", line 4708, in _literal_as_text
    return _literal_as(element, _no_text_coercion)
  File "c:\program files\python38\lib\site-packages\sqlalchemy\sql\elements.py", line 4694, in _literal_as
    return text_fallback(element)
  File "c:\program files\python38\lib\site-packages\sqlalchemy\sql\elements.py", line 4735, in _no_text_coercion
    util.raise_(
  File "c:\program files\python38\lib\site-packages\sqlalchemy\util\compat.py", line 178, in raise_
    raise exception
sqlalchemy.exc.ArgumentError: Textual SQL expression 'randomerg.ru' should be explicitly declared as text('randomerg.ru')
2020-09-11 15:52:29,935:app:INFO:user 1 deleted ticket
2020-09-11 15:52:35,228:app:INFO:manager 2  accessed tickets list
2020-09-11 15:52:35,250:app:INFO:manager 2  accessed tickets list
2020-09-11 16:00:00,141:app:INFO:manager 2  accessed tickets list
2020-09-11 16:00:00,181:app:INFO:manager 2 verified ticket 4
2020-09-11 16:00:00,191:app:INFO:manager 2  accessed tickets list
2020-09-11 16:00:04,288:app:INFO:manager 2  accessed tickets list
2020-09-11 16:00:05,511:app:ERROR:Exception on /place_ticket [POST]
Traceback (most recent call last):
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\program files\python38\lib\site-packages\flask_jwt_extended\view_decorators.py", line 108, in wrapper
    return fn(*args, **kwargs)
  File "C:\localhost\GitHub\feruc\RaillWayTickets\server-side\app\decorators.py", line 14, in decorated_f
    return f(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_apispec\annotations.py", line 118, in wrapped
    return wrapper(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_apispec\wrapper.py", line 33, in __call__
    response = self.call_view(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_apispec\wrapper.py", line 56, in call_view
    return self.func(*args, **kwargs)
  File "C:\localhost\GitHub\feruc\RaillWayTickets\server-side\app\routes\main\views.py", line 110, in place_ticket
    user = session.query(User).filter(kwargs.get('buyer_email')).one_or_none()
  File "<string>", line 2, in filter
  File "c:\program files\python38\lib\site-packages\sqlalchemy\orm\base.py", line 227, in generate
    fn(self, *args[1:], **kw)
  File "c:\program files\python38\lib\site-packages\sqlalchemy\orm\query.py", line 1859, in filter
    criterion = expression._expression_literal_as_text(criterion)
  File "c:\program files\python38\lib\site-packages\sqlalchemy\sql\elements.py", line 4685, in _expression_literal_as_text
    return _literal_as_text(element)
  File "c:\program files\python38\lib\site-packages\sqlalchemy\sql\elements.py", line 4708, in _literal_as_text
    return _literal_as(element, _no_text_coercion)
  File "c:\program files\python38\lib\site-packages\sqlalchemy\sql\elements.py", line 4694, in _literal_as
    return text_fallback(element)
  File "c:\program files\python38\lib\site-packages\sqlalchemy\sql\elements.py", line 4735, in _no_text_coercion
    util.raise_(
  File "c:\program files\python38\lib\site-packages\sqlalchemy\util\compat.py", line 178, in raise_
    raise exception
sqlalchemy.exc.ArgumentError: Textual SQL expression 'randomerg.ru' should be explicitly declared as text('randomerg.ru')
2020-09-11 16:00:16,541:app:INFO:manager 2  accessed tickets list
2020-09-11 16:00:16,581:app:INFO:manager 2  accessed tickets list
2020-09-11 16:05:19,451:app:INFO:manager 2  accessed tickets list
2020-09-11 16:05:19,481:app:INFO:manager 2 verified ticket 4
2020-09-11 16:05:19,491:app:INFO:manager 2  accessed tickets list
2020-09-11 16:05:23,950:app:INFO:manager 2  accessed tickets list
2020-09-11 16:05:25,081:app:ERROR:Exception on /place_ticket [POST]
Traceback (most recent call last):
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\program files\python38\lib\site-packages\flask_jwt_extended\view_decorators.py", line 108, in wrapper
    return fn(*args, **kwargs)
  File "C:\localhost\GitHub\feruc\RaillWayTickets\server-side\app\decorators.py", line 14, in decorated_f
    return f(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_apispec\annotations.py", line 118, in wrapped
    return wrapper(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_apispec\wrapper.py", line 33, in __call__
    response = self.call_view(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_apispec\wrapper.py", line 56, in call_view
    return self.func(*args, **kwargs)
  File "C:\localhost\GitHub\feruc\RaillWayTickets\server-side\app\routes\main\views.py", line 110, in place_ticket
    user = session.query(User).filter(kwargs.get('buyer_email')).one_or_none()
  File "<string>", line 2, in filter
  File "c:\program files\python38\lib\site-packages\sqlalchemy\orm\base.py", line 227, in generate
    fn(self, *args[1:], **kw)
  File "c:\program files\python38\lib\site-packages\sqlalchemy\orm\query.py", line 1859, in filter
    criterion = expression._expression_literal_as_text(criterion)
  File "c:\program files\python38\lib\site-packages\sqlalchemy\sql\elements.py", line 4685, in _expression_literal_as_text
    return _literal_as_text(element)
  File "c:\program files\python38\lib\site-packages\sqlalchemy\sql\elements.py", line 4708, in _literal_as_text
    return _literal_as(element, _no_text_coercion)
  File "c:\program files\python38\lib\site-packages\sqlalchemy\sql\elements.py", line 4694, in _literal_as
    return text_fallback(element)
  File "c:\program files\python38\lib\site-packages\sqlalchemy\sql\elements.py", line 4735, in _no_text_coercion
    util.raise_(
  File "c:\program files\python38\lib\site-packages\sqlalchemy\util\compat.py", line 178, in raise_
    raise exception
sqlalchemy.exc.ArgumentError: Textual SQL expression 'randomerg.ru' should be explicitly declared as text('randomerg.ru')
2020-09-11 16:05:36,632:app:INFO:manager 2  accessed tickets list
2020-09-11 16:05:36,667:app:INFO:manager 2  accessed tickets list
2020-09-11 16:10:07,847:app:INFO:manager 2  accessed tickets list
2020-09-11 16:10:07,897:app:INFO:manager 2 verified ticket 4
2020-09-11 16:10:07,906:app:INFO:manager 2  accessed tickets list
2020-09-11 16:10:11,922:app:INFO:manager 2  accessed tickets list
2020-09-11 16:10:13,187:app:ERROR:Exception on /place_ticket [POST]
Traceback (most recent call last):
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\program files\python38\lib\site-packages\flask_jwt_extended\view_decorators.py", line 108, in wrapper
    return fn(*args, **kwargs)
  File "C:\localhost\GitHub\feruc\RaillWayTickets\server-side\app\decorators.py", line 14, in decorated_f
    return f(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_apispec\annotations.py", line 118, in wrapped
    return wrapper(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_apispec\wrapper.py", line 33, in __call__
    response = self.call_view(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_apispec\wrapper.py", line 56, in call_view
    return self.func(*args, **kwargs)
  File "C:\localhost\GitHub\feruc\RaillWayTickets\server-side\app\routes\main\views.py", line 110, in place_ticket
    user = session.query(User).filter(kwargs.get('buyer_email')).one_or_none()
  File "<string>", line 2, in filter
  File "c:\program files\python38\lib\site-packages\sqlalchemy\orm\base.py", line 227, in generate
    fn(self, *args[1:], **kw)
  File "c:\program files\python38\lib\site-packages\sqlalchemy\orm\query.py", line 1859, in filter
    criterion = expression._expression_literal_as_text(criterion)
  File "c:\program files\python38\lib\site-packages\sqlalchemy\sql\elements.py", line 4685, in _expression_literal_as_text
    return _literal_as_text(element)
  File "c:\program files\python38\lib\site-packages\sqlalchemy\sql\elements.py", line 4708, in _literal_as_text
    return _literal_as(element, _no_text_coercion)
  File "c:\program files\python38\lib\site-packages\sqlalchemy\sql\elements.py", line 4694, in _literal_as
    return text_fallback(element)
  File "c:\program files\python38\lib\site-packages\sqlalchemy\sql\elements.py", line 4735, in _no_text_coercion
    util.raise_(
  File "c:\program files\python38\lib\site-packages\sqlalchemy\util\compat.py", line 178, in raise_
    raise exception
sqlalchemy.exc.ArgumentError: Textual SQL expression 'randomerg.ru' should be explicitly declared as text('randomerg.ru')
2020-09-11 16:10:24,226:app:INFO:manager 2  accessed tickets list
2020-09-11 16:10:24,257:app:INFO:manager 2  accessed tickets list
2020-09-11 16:14:44,386:app:INFO:manager 2  accessed tickets list
2020-09-11 16:14:44,426:app:INFO:manager 2 verified ticket 4
2020-09-11 16:14:44,436:app:INFO:manager 2  accessed tickets list
2020-09-11 16:14:48,676:app:INFO:manager 2  accessed tickets list
2020-09-11 16:14:50,191:app:ERROR:Exception on /place_ticket [POST]
Traceback (most recent call last):
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\program files\python38\lib\site-packages\flask_jwt_extended\view_decorators.py", line 108, in wrapper
    return fn(*args, **kwargs)
  File "C:\localhost\GitHub\feruc\RaillWayTickets\server-side\app\decorators.py", line 14, in decorated_f
    return f(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_apispec\annotations.py", line 118, in wrapped
    return wrapper(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_apispec\wrapper.py", line 33, in __call__
    response = self.call_view(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_apispec\wrapper.py", line 56, in call_view
    return self.func(*args, **kwargs)
  File "C:\localhost\GitHub\feruc\RaillWayTickets\server-side\app\routes\main\views.py", line 110, in place_ticket
    user = session.query(User).filter(kwargs.get('buyer_email')).one_or_none()
  File "<string>", line 2, in filter
  File "c:\program files\python38\lib\site-packages\sqlalchemy\orm\base.py", line 227, in generate
    fn(self, *args[1:], **kw)
  File "c:\program files\python38\lib\site-packages\sqlalchemy\orm\query.py", line 1859, in filter
    criterion = expression._expression_literal_as_text(criterion)
  File "c:\program files\python38\lib\site-packages\sqlalchemy\sql\elements.py", line 4685, in _expression_literal_as_text
    return _literal_as_text(element)
  File "c:\program files\python38\lib\site-packages\sqlalchemy\sql\elements.py", line 4708, in _literal_as_text
    return _literal_as(element, _no_text_coercion)
  File "c:\program files\python38\lib\site-packages\sqlalchemy\sql\elements.py", line 4694, in _literal_as
    return text_fallback(element)
  File "c:\program files\python38\lib\site-packages\sqlalchemy\sql\elements.py", line 4735, in _no_text_coercion
    util.raise_(
  File "c:\program files\python38\lib\site-packages\sqlalchemy\util\compat.py", line 178, in raise_
    raise exception
sqlalchemy.exc.ArgumentError: Textual SQL expression 'randomerg.ru' should be explicitly declared as text('randomerg.ru')
2020-09-11 16:15:02,326:app:INFO:manager 2  accessed tickets list
2020-09-11 16:15:02,366:app:INFO:manager 2  accessed tickets list
2020-09-11 16:16:21,826:app:INFO:manager 2  accessed tickets list
2020-09-11 16:16:21,856:app:INFO:manager 2 verified ticket 4
2020-09-11 16:16:21,866:app:INFO:manager 2  accessed tickets list
2020-09-11 16:16:25,986:app:INFO:manager 2  accessed tickets list
2020-09-11 16:16:27,326:app:ERROR:Exception on /place_ticket [POST]
Traceback (most recent call last):
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\program files\python38\lib\site-packages\flask_jwt_extended\view_decorators.py", line 108, in wrapper
    return fn(*args, **kwargs)
  File "C:\localhost\GitHub\feruc\RaillWayTickets\server-side\app\decorators.py", line 14, in decorated_f
    return f(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_apispec\annotations.py", line 118, in wrapped
    return wrapper(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_apispec\wrapper.py", line 33, in __call__
    response = self.call_view(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_apispec\wrapper.py", line 56, in call_view
    return self.func(*args, **kwargs)
  File "C:\localhost\GitHub\feruc\RaillWayTickets\server-side\app\routes\main\views.py", line 110, in place_ticket
    user = session.query(User).filter(kwargs.get('buyer_email')).one_or_none()
  File "<string>", line 2, in filter
  File "c:\program files\python38\lib\site-packages\sqlalchemy\orm\base.py", line 227, in generate
    fn(self, *args[1:], **kw)
  File "c:\program files\python38\lib\site-packages\sqlalchemy\orm\query.py", line 1859, in filter
    criterion = expression._expression_literal_as_text(criterion)
  File "c:\program files\python38\lib\site-packages\sqlalchemy\sql\elements.py", line 4685, in _expression_literal_as_text
    return _literal_as_text(element)
  File "c:\program files\python38\lib\site-packages\sqlalchemy\sql\elements.py", line 4708, in _literal_as_text
    return _literal_as(element, _no_text_coercion)
  File "c:\program files\python38\lib\site-packages\sqlalchemy\sql\elements.py", line 4694, in _literal_as
    return text_fallback(element)
  File "c:\program files\python38\lib\site-packages\sqlalchemy\sql\elements.py", line 4735, in _no_text_coercion
    util.raise_(
  File "c:\program files\python38\lib\site-packages\sqlalchemy\util\compat.py", line 178, in raise_
    raise exception
sqlalchemy.exc.ArgumentError: Textual SQL expression 'randomerg.ru' should be explicitly declared as text('randomerg.ru')
2020-09-11 16:16:36,203:app:INFO:manager 2  accessed tickets list
2020-09-11 16:16:36,234:app:INFO:manager 2  accessed tickets list
2020-09-11 16:20:27,079:app:INFO:manager 2  accessed tickets list
2020-09-11 16:20:27,100:app:INFO:manager 2 verified ticket 4
2020-09-11 16:20:27,106:app:INFO:manager 2  accessed tickets list
2020-09-11 16:20:30,403:app:INFO:manager 2  accessed tickets list
2020-09-11 16:20:31,399:app:ERROR:Exception on /place_ticket [POST]
Traceback (most recent call last):
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\program files\python38\lib\site-packages\flask_jwt_extended\view_decorators.py", line 108, in wrapper
    return fn(*args, **kwargs)
  File "C:\localhost\GitHub\feruc\RaillWayTickets\server-side\app\decorators.py", line 14, in decorated_f
    return f(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_apispec\annotations.py", line 118, in wrapped
    return wrapper(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_apispec\wrapper.py", line 33, in __call__
    response = self.call_view(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_apispec\wrapper.py", line 56, in call_view
    return self.func(*args, **kwargs)
  File "C:\localhost\GitHub\feruc\RaillWayTickets\server-side\app\routes\main\views.py", line 110, in place_ticket
    user = session.query(User).filter(kwargs.get('buyer_email')).one_or_none()
  File "<string>", line 2, in filter
  File "c:\program files\python38\lib\site-packages\sqlalchemy\orm\base.py", line 227, in generate
    fn(self, *args[1:], **kw)
  File "c:\program files\python38\lib\site-packages\sqlalchemy\orm\query.py", line 1859, in filter
    criterion = expression._expression_literal_as_text(criterion)
  File "c:\program files\python38\lib\site-packages\sqlalchemy\sql\elements.py", line 4685, in _expression_literal_as_text
    return _literal_as_text(element)
  File "c:\program files\python38\lib\site-packages\sqlalchemy\sql\elements.py", line 4708, in _literal_as_text
    return _literal_as(element, _no_text_coercion)
  File "c:\program files\python38\lib\site-packages\sqlalchemy\sql\elements.py", line 4694, in _literal_as
    return text_fallback(element)
  File "c:\program files\python38\lib\site-packages\sqlalchemy\sql\elements.py", line 4735, in _no_text_coercion
    util.raise_(
  File "c:\program files\python38\lib\site-packages\sqlalchemy\util\compat.py", line 178, in raise_
    raise exception
sqlalchemy.exc.ArgumentError: Textual SQL expression 'randomerg.ru' should be explicitly declared as text('randomerg.ru')
2020-09-11 16:20:37,602:app:INFO:user 1 deleted ticket
2020-09-11 16:20:37,632:app:INFO:user 2 deleted ticket
2020-09-11 16:20:42,906:app:INFO:manager 2  accessed tickets list
2020-09-11 16:20:42,942:app:INFO:manager 2  accessed tickets list
2020-09-11 16:22:14,491:app:INFO:manager 2  accessed tickets list
2020-09-11 16:22:14,521:app:INFO:manager 2 verified ticket 4
2020-09-11 16:22:14,531:app:INFO:manager 2  accessed tickets list
2020-09-11 16:22:18,451:app:INFO:manager 2  accessed tickets list
2020-09-11 16:22:19,622:app:ERROR:Exception on /place_ticket [POST]
Traceback (most recent call last):
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\program files\python38\lib\site-packages\flask_jwt_extended\view_decorators.py", line 108, in wrapper
    return fn(*args, **kwargs)
  File "C:\localhost\GitHub\feruc\RaillWayTickets\server-side\app\decorators.py", line 14, in decorated_f
    return f(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_apispec\annotations.py", line 118, in wrapped
    return wrapper(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_apispec\wrapper.py", line 33, in __call__
    response = self.call_view(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_apispec\wrapper.py", line 56, in call_view
    return self.func(*args, **kwargs)
  File "C:\localhost\GitHub\feruc\RaillWayTickets\server-side\app\routes\main\views.py", line 110, in place_ticket
    user = session.query(User).filter(kwargs.get('buyer_email')).one_or_none()
  File "<string>", line 2, in filter
  File "c:\program files\python38\lib\site-packages\sqlalchemy\orm\base.py", line 227, in generate
    fn(self, *args[1:], **kw)
  File "c:\program files\python38\lib\site-packages\sqlalchemy\orm\query.py", line 1859, in filter
    criterion = expression._expression_literal_as_text(criterion)
  File "c:\program files\python38\lib\site-packages\sqlalchemy\sql\elements.py", line 4685, in _expression_literal_as_text
    return _literal_as_text(element)
  File "c:\program files\python38\lib\site-packages\sqlalchemy\sql\elements.py", line 4708, in _literal_as_text
    return _literal_as(element, _no_text_coercion)
  File "c:\program files\python38\lib\site-packages\sqlalchemy\sql\elements.py", line 4694, in _literal_as
    return text_fallback(element)
  File "c:\program files\python38\lib\site-packages\sqlalchemy\sql\elements.py", line 4735, in _no_text_coercion
    util.raise_(
  File "c:\program files\python38\lib\site-packages\sqlalchemy\util\compat.py", line 178, in raise_
    raise exception
sqlalchemy.exc.ArgumentError: Textual SQL expression 'randomerg.ru' should be explicitly declared as text('randomerg.ru')
2020-09-11 16:22:25,192:app:INFO:user 1 deleted ticket
2020-09-11 16:22:25,232:app:INFO:user 2 deleted ticket
2020-09-11 16:22:30,366:app:INFO:manager 2  accessed tickets list
2020-09-11 16:22:30,392:app:INFO:manager 2  accessed tickets list
2020-09-11 16:25:13,030:app:INFO:manager 2  accessed tickets list
2020-09-11 16:25:13,091:app:INFO:manager 2 verified ticket 4
2020-09-11 16:25:13,105:app:INFO:manager 2  accessed tickets list
2020-09-11 16:25:15,470:app:INFO:manager 2  accessed tickets list
2020-09-11 16:25:16,425:app:WARNING:Invalid input params: {'buyer_email': ['Not a valid email address.']}
2020-09-11 16:25:16,435:app:WARNING:Invalid input params: {'buyer_email': ['Not a valid email address.']}
2020-09-11 16:25:22,245:app:INFO:user 1 deleted ticket
2020-09-11 16:25:22,431:app:INFO:user 2 deleted ticket
2020-09-11 16:25:27,905:app:INFO:manager 2  accessed tickets list
2020-09-11 16:25:27,935:app:INFO:manager 2  accessed tickets list
2020-09-11 16:27:18,025:app:INFO:manager 2  accessed tickets list
2020-09-11 16:27:18,105:app:INFO:manager 2 verified ticket 4
2020-09-11 16:27:18,145:app:INFO:manager 2  accessed tickets list
2020-09-11 16:27:22,226:app:INFO:manager 2  accessed tickets list
2020-09-11 16:27:23,405:app:WARNING:Invalid input params: {'buyer_email': ['Not a valid email address.']}
2020-09-11 16:27:23,415:app:ERROR:Exception on /place_ticket [POST]
Traceback (most recent call last):
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\program files\python38\lib\site-packages\flask_jwt_extended\view_decorators.py", line 108, in wrapper
    return fn(*args, **kwargs)
  File "C:\localhost\GitHub\feruc\RaillWayTickets\server-side\app\decorators.py", line 14, in decorated_f
    return f(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_apispec\annotations.py", line 118, in wrapped
    return wrapper(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_apispec\wrapper.py", line 33, in __call__
    response = self.call_view(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_apispec\wrapper.py", line 56, in call_view
    return self.func(*args, **kwargs)
  File "C:\localhost\GitHub\feruc\RaillWayTickets\server-side\app\routes\main\views.py", line 110, in place_ticket
    user = session.query(User).filter(kwargs.get('buyer_email')).one_or_none()
  File "<string>", line 2, in filter
  File "c:\program files\python38\lib\site-packages\sqlalchemy\orm\base.py", line 227, in generate
    fn(self, *args[1:], **kw)
  File "c:\program files\python38\lib\site-packages\sqlalchemy\orm\query.py", line 1859, in filter
    criterion = expression._expression_literal_as_text(criterion)
  File "c:\program files\python38\lib\site-packages\sqlalchemy\sql\elements.py", line 4685, in _expression_literal_as_text
    return _literal_as_text(element)
  File "c:\program files\python38\lib\site-packages\sqlalchemy\sql\elements.py", line 4708, in _literal_as_text
    return _literal_as(element, _no_text_coercion)
  File "c:\program files\python38\lib\site-packages\sqlalchemy\sql\elements.py", line 4694, in _literal_as
    return text_fallback(element)
  File "c:\program files\python38\lib\site-packages\sqlalchemy\sql\elements.py", line 4735, in _no_text_coercion
    util.raise_(
  File "c:\program files\python38\lib\site-packages\sqlalchemy\util\compat.py", line 178, in raise_
    raise exception
sqlalchemy.exc.ArgumentError: Textual SQL expression 'testmail@mail.com' should be explicitly declared as text('testmail@mail.com')
2020-09-11 16:27:30,215:app:INFO:user 1 deleted ticket
2020-09-11 16:27:30,255:app:INFO:user 2 deleted ticket
2020-09-11 16:27:35,295:app:INFO:manager 2  accessed tickets list
2020-09-11 16:27:35,335:app:INFO:manager 2  accessed tickets list
2020-09-11 16:32:46,958:app:INFO:manager 2  accessed tickets list
2020-09-11 16:32:46,998:app:INFO:manager 2 verified ticket 4
2020-09-11 16:32:47,008:app:INFO:manager 2  accessed tickets list
2020-09-11 16:32:51,088:app:INFO:manager 2  accessed tickets list
2020-09-11 16:32:52,298:app:WARNING:Invalid input params: {'buyer_email': ['Not a valid email address.']}
2020-09-11 16:32:58,228:app:INFO:user 1 deleted ticket
2020-09-11 16:32:58,268:app:INFO:user 2 deleted ticket
2020-09-11 16:33:03,653:app:INFO:manager 2  accessed tickets list
2020-09-11 16:33:03,678:app:INFO:manager 2  accessed tickets list
2020-09-11 16:34:44,549:app:INFO:manager 2  accessed tickets list
2020-09-11 16:34:44,581:app:INFO:manager 2 verified ticket 4
2020-09-11 16:34:44,596:app:INFO:manager 2  accessed tickets list
2020-09-11 16:34:48,735:app:INFO:manager 2  accessed tickets list
2020-09-11 16:34:49,985:app:WARNING:Invalid input params: {'buyer_email': ['Not a valid email address.']}
2020-09-11 16:34:50,001:app:WARNING:Invalid input params: {'buyer_email': ['Not a valid email address.']}
2020-09-11 16:34:56,058:app:INFO:user 1 deleted ticket
2020-09-11 16:34:56,080:app:INFO:user 2 deleted ticket
2020-09-11 16:35:01,157:app:INFO:manager 2  accessed tickets list
2020-09-11 16:35:01,179:app:INFO:manager 2  accessed tickets list
2020-09-11 16:37:26,591:app:INFO:manager 2  accessed tickets list
2020-09-11 16:37:26,622:app:INFO:manager 2 verified ticket 4
2020-09-11 16:37:26,638:app:INFO:manager 2  accessed tickets list
2020-09-11 16:37:30,550:app:INFO:manager 2  accessed tickets list
2020-09-11 16:37:31,722:app:WARNING:Invalid input params: {'buyer_email': ['Not a valid email address.']}
2020-09-11 16:37:31,722:app:WARNING:Invalid input params: {'buyer_email': ['Not a valid email address.']}
2020-09-11 16:37:37,254:app:INFO:user 1 deleted ticket
2020-09-11 16:37:37,285:app:INFO:user 2 deleted ticket
2020-09-11 16:37:42,335:app:INFO:manager 2  accessed tickets list
2020-09-11 16:37:42,358:app:INFO:manager 2  accessed tickets list
2020-09-11 16:38:59,202:app:INFO:manager 2  accessed tickets list
2020-09-11 16:38:59,233:app:INFO:manager 2 verified ticket 4
2020-09-11 16:38:59,249:app:INFO:manager 2  accessed tickets list
2020-09-11 16:39:03,129:app:INFO:manager 2  accessed tickets list
2020-09-11 16:39:04,417:app:WARNING:Invalid input params: {'buyer_email': ['Not a valid email address.']}
2020-09-11 16:39:04,433:app:ERROR:Exception on /place_ticket [POST]
Traceback (most recent call last):
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\feruc\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\program files\python38\lib\site-packages\flask_jwt_extended\view_decorators.py", line 108, in wrapper
    return fn(*args, **kwargs)
  File "C:\localhost\GitHub\feruc\RaillWayTickets\server-side\app\decorators.py", line 14, in decorated_f
    return f(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_apispec\annotations.py", line 118, in wrapped
    return wrapper(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_apispec\wrapper.py", line 33, in __call__
    response = self.call_view(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\flask_apispec\wrapper.py", line 56, in call_view
    return self.func(*args, **kwargs)
  File "C:\localhost\GitHub\feruc\RaillWayTickets\server-side\app\routes\main\views.py", line 113, in place_ticket
    user_id = user[0].id
TypeError: 'User' object is not subscriptable
2020-09-11 16:39:10,008:app:INFO:user 1 deleted ticket
2020-09-11 16:39:10,046:app:INFO:user 2 deleted ticket
2020-09-11 16:39:14,585:app:INFO:manager 2  accessed tickets list
2020-09-11 16:39:14,616:app:INFO:manager 2  accessed tickets list
2020-09-11 16:40:43,265:app:INFO:manager 2  accessed tickets list
2020-09-11 16:40:43,296:app:INFO:manager 2 verified ticket 4
2020-09-11 16:40:43,296:app:INFO:manager 2  accessed tickets list
2020-09-11 16:40:47,107:app:INFO:manager 2  accessed tickets list
2020-09-11 16:40:48,310:app:WARNING:Invalid input params: {'buyer_email': ['Not a valid email address.']}
2020-09-11 16:40:48,379:app:INFO:manager 2  accessed tickets list
2020-09-11 16:40:53,969:app:INFO:user 1 deleted ticket
2020-09-11 16:40:54,007:app:INFO:user 2 deleted ticket
2020-09-11 16:40:59,253:app:INFO:manager 2  accessed tickets list
2020-09-11 16:40:59,284:app:INFO:manager 2  accessed tickets list
2020-09-11 16:41:47,078:app:INFO:manager 2  accessed tickets list
2020-09-11 16:41:47,109:app:INFO:manager 2 verified ticket 4
2020-09-11 16:41:47,125:app:INFO:manager 2  accessed tickets list
2020-09-11 16:41:51,120:app:INFO:manager 2  accessed tickets list
2020-09-11 16:41:52,324:app:WARNING:Invalid input params: {'buyer_email': ['Not a valid email address.']}
2020-09-11 16:41:52,386:app:INFO:manager 2  accessed tickets list
2020-09-11 16:41:52,408:app:INFO:manager 2  accessed tickets list
2020-09-11 16:41:57,447:app:INFO:user 1 deleted ticket
2020-09-11 16:41:57,478:app:INFO:user 2 deleted ticket
2020-09-11 16:42:02,545:app:INFO:manager 2  accessed tickets list
2020-09-11 16:42:02,575:app:INFO:manager 2  accessed tickets list
2020-09-11 16:56:35,942:app:INFO:manager 2  accessed tickets list
2020-09-11 16:56:35,992:app:INFO:manager 2 verified ticket 4
2020-09-11 16:56:36,007:app:INFO:manager 2  accessed tickets list
2020-09-11 16:56:40,232:app:INFO:manager 2  accessed tickets list
2020-09-11 16:56:41,452:app:WARNING:Invalid input params: {'buyer_email': ['Not a valid email address.']}
2020-09-11 16:56:41,502:app:INFO:manager 2  accessed tickets list
2020-09-11 16:56:41,542:app:INFO:manager 2  accessed tickets list
2020-09-11 16:56:46,712:app:INFO:user 1 deleted ticket
2020-09-11 16:56:46,742:app:INFO:user 2 deleted ticket
2020-09-11 16:56:52,262:app:INFO:manager 2  accessed tickets list
2020-09-11 16:56:52,296:app:INFO:manager 2  accessed tickets list
2020-09-11 17:00:00,927:app:INFO:manager 2  accessed tickets list
2020-09-11 17:00:00,962:app:INFO:manager 2 verified ticket 4
2020-09-11 17:00:00,976:app:INFO:manager 2  accessed tickets list
2020-09-11 17:00:04,886:app:INFO:manager 2  accessed tickets list
2020-09-11 17:00:06,051:app:WARNING:Invalid input params: {'buyer_email': ['Not a valid email address.']}
2020-09-11 17:00:06,112:app:INFO:manager 2  accessed tickets list
2020-09-11 17:00:06,141:app:INFO:manager 2  accessed tickets list
2020-09-11 17:00:11,191:app:INFO:user 1 deleted ticket
2020-09-11 17:00:11,221:app:INFO:user 2 deleted ticket
2020-09-11 17:00:16,421:app:INFO:manager 2  accessed tickets list
2020-09-11 17:00:16,451:app:INFO:manager 2  accessed tickets list
2020-09-11 17:41:22,467:app:INFO:manager 2  accessed tickets list
2020-09-11 17:41:22,514:app:INFO:manager 2 verified ticket 4
2020-09-11 17:41:22,529:app:INFO:manager 2  accessed tickets list
2020-09-11 17:41:27,167:app:INFO:manager 2  accessed tickets list
2020-09-11 17:41:28,386:app:WARNING:Invalid input params: {'buyer_email': ['Not a valid email address.']}
2020-09-11 17:41:28,440:app:INFO:manager 2  accessed tickets list
2020-09-11 17:41:28,471:app:INFO:manager 2  accessed tickets list
2020-09-11 17:41:33,580:app:INFO:user 1 deleted ticket
2020-09-11 17:41:33,611:app:INFO:user 2 deleted ticket
2020-09-11 17:41:38,810:app:INFO:manager 2  accessed tickets list
2020-09-11 17:41:38,841:app:INFO:manager 2  accessed tickets list
2020-09-11 17:42:12,520:app:INFO:manager 2  accessed tickets list
2020-09-11 17:42:12,551:app:INFO:manager 2 verified ticket 4
2020-09-11 17:42:12,566:app:INFO:manager 2  accessed tickets list
2020-09-11 17:42:16,829:app:INFO:manager 2  accessed tickets list
2020-09-11 17:42:17,994:app:WARNING:Invalid input params: {'buyer_email': ['Not a valid email address.']}
2020-09-11 17:42:18,048:app:INFO:manager 2  accessed tickets list
2020-09-11 17:42:18,079:app:INFO:manager 2  accessed tickets list
2020-09-11 17:42:23,528:app:INFO:user 1 deleted ticket
2020-09-11 17:42:23,553:app:INFO:user 2 deleted ticket
2020-09-11 17:42:28,800:app:INFO:manager 2  accessed tickets list
2020-09-11 17:42:28,831:app:INFO:manager 2  accessed tickets list
2020-09-11 17:43:52,149:app:INFO:manager 2  accessed tickets list
2020-09-11 17:43:52,196:app:INFO:manager 2 verified ticket 4
2020-09-11 17:43:52,196:app:INFO:manager 2  accessed tickets list
2020-09-11 17:43:56,662:app:INFO:manager 2  accessed tickets list
2020-09-11 17:43:57,828:app:WARNING:Invalid input params: {'buyer_email': ['Not a valid email address.']}
2020-09-11 17:43:57,881:app:INFO:manager 2  accessed tickets list
2020-09-11 17:43:57,912:app:INFO:manager 2  accessed tickets list
2020-09-11 17:44:03,281:app:INFO:user 1 deleted ticket
2020-09-11 17:44:03,998:app:INFO:user 2 deleted ticket
2020-09-11 17:44:10,457:app:INFO:manager 2  accessed tickets list
2020-09-11 17:44:10,488:app:INFO:manager 2  accessed tickets list
2020-09-11 17:44:49,030:app:INFO:manager 2  accessed tickets list
2020-09-11 17:44:49,068:app:INFO:manager 2 verified ticket 4
2020-09-11 17:44:49,068:app:INFO:manager 2  accessed tickets list
2020-09-11 17:44:53,609:app:INFO:manager 2  accessed tickets list
2020-09-11 17:44:54,781:app:WARNING:Invalid input params: {'buyer_email': ['Not a valid email address.']}
2020-09-11 17:44:54,843:app:INFO:manager 2  accessed tickets list
2020-09-11 17:44:54,881:app:INFO:manager 2  accessed tickets list
2020-09-11 17:45:02,527:app:INFO:user 1 deleted ticket
2020-09-11 17:45:02,565:app:INFO:user 2 deleted ticket
2020-09-11 17:45:07,645:app:INFO:manager 2  accessed tickets list
2020-09-11 17:45:07,674:app:INFO:manager 2  accessed tickets list
2020-09-11 17:47:27,378:app:INFO:manager 2  accessed tickets list
2020-09-11 17:47:27,409:app:INFO:manager 2 verified ticket 4
2020-09-11 17:47:27,425:app:INFO:manager 2  accessed tickets list
2020-09-11 17:47:31,991:app:INFO:manager 2  accessed tickets list
2020-09-11 17:47:33,326:app:WARNING:Invalid input params: {'buyer_email': ['Not a valid email address.']}
2020-09-11 17:47:33,380:app:INFO:manager 2  accessed tickets list
2020-09-11 17:47:33,411:app:INFO:manager 2  accessed tickets list
2020-09-11 17:47:38,439:app:INFO:user 1 deleted ticket
2020-09-11 17:47:38,480:app:INFO:user 2 deleted ticket
2020-09-11 17:47:42,892:app:INFO:manager 2  accessed tickets list
2020-09-11 17:47:42,908:app:INFO:manager 2  accessed tickets list
2020-09-11 17:48:53,955:app:INFO:manager 2  accessed tickets list
2020-09-11 17:48:53,986:app:INFO:manager 2 verified ticket 4
2020-09-11 17:48:54,002:app:INFO:manager 2  accessed tickets list
2020-09-11 17:48:57,782:app:INFO:manager 2  accessed tickets list
2020-09-11 17:48:58,936:app:WARNING:Invalid input params: {'buyer_email': ['Not a valid email address.']}
2020-09-11 17:48:58,980:app:INFO:manager 2  accessed tickets list
2020-09-11 17:48:59,011:app:INFO:manager 2  accessed tickets list
2020-09-11 17:49:04,104:app:INFO:user 1 deleted ticket
2020-09-11 17:49:04,129:app:INFO:user 2 deleted ticket
2020-09-11 17:49:09,117:app:INFO:manager 2  accessed tickets list
2020-09-11 17:49:09,146:app:INFO:manager 2  accessed tickets list
2020-09-11 17:49:59,009:app:INFO:manager 2  accessed tickets list
2020-09-11 17:49:59,047:app:INFO:manager 2 verified ticket 4
2020-09-11 17:49:59,047:app:INFO:manager 2  accessed tickets list
2020-09-11 17:50:03,384:app:INFO:manager 2  accessed tickets list
2020-09-11 17:50:04,551:app:WARNING:Invalid input params: {'buyer_email': ['Not a valid email address.']}
2020-09-11 17:50:04,602:app:INFO:manager 2  accessed tickets list
2020-09-11 17:50:04,625:app:INFO:manager 2  accessed tickets list
2020-09-11 17:50:09,653:app:INFO:user 1 deleted ticket
2020-09-11 17:50:09,679:app:INFO:user 2 deleted ticket
2020-09-11 17:50:14,829:app:INFO:manager 2  accessed tickets list
2020-09-11 17:50:14,852:app:INFO:manager 2  accessed tickets list
2020-09-11 17:50:52,643:app:INFO:manager 2  accessed tickets list
2020-09-11 17:50:52,674:app:INFO:manager 2 verified ticket 4
2020-09-11 17:50:52,674:app:INFO:manager 2  accessed tickets list
2020-09-11 17:50:57,449:app:INFO:manager 2  accessed tickets list
2020-09-11 17:50:58,706:app:WARNING:Invalid input params: {'buyer_email': ['Not a valid email address.']}
2020-09-11 17:50:58,753:app:INFO:manager 2  accessed tickets list
2020-09-11 17:50:58,791:app:INFO:manager 2  accessed tickets list
2020-09-11 17:51:04,117:app:INFO:user 1 deleted ticket
2020-09-11 17:51:04,148:app:INFO:user 2 deleted ticket
2020-09-11 17:51:09,464:app:INFO:manager 2  accessed tickets list
2020-09-11 17:51:09,502:app:INFO:manager 2  accessed tickets list
2020-09-11 17:52:42,867:app:INFO:manager 2  accessed tickets list
2020-09-11 17:52:42,882:app:INFO:manager 2 verified ticket 4
2020-09-11 17:52:42,898:app:INFO:manager 2  accessed tickets list
2020-09-11 17:52:47,223:app:INFO:manager 2  accessed tickets list
2020-09-11 17:52:48,512:app:WARNING:Invalid input params: {'buyer_email': ['Not a valid email address.']}
2020-09-11 17:52:48,566:app:INFO:manager 2  accessed tickets list
2020-09-11 17:52:48,597:app:INFO:manager 2  accessed tickets list
2020-09-11 17:52:54,139:app:INFO:user 1 deleted ticket
2020-09-11 17:52:54,170:app:INFO:user 2 deleted ticket
2020-09-11 17:52:59,252:app:INFO:manager 2  accessed tickets list
2020-09-11 17:52:59,283:app:INFO:manager 2  accessed tickets list
2020-09-11 18:28:05,029:app:INFO:manager 2  accessed tickets list
2020-09-11 18:28:05,066:app:INFO:manager 2 verified ticket 4
2020-09-11 18:28:05,066:app:INFO:manager 2  accessed tickets list
2020-09-11 18:28:09,461:app:INFO:manager 2  accessed tickets list
2020-09-11 18:28:10,664:app:WARNING:Invalid input params: {'buyer_email': ['Not a valid email address.']}
2020-09-11 18:28:10,727:app:INFO:manager 2  accessed tickets list
2020-09-11 18:28:10,765:app:INFO:manager 2  accessed tickets list
2020-09-11 18:28:15,503:app:INFO:user 1 deleted ticket
2020-09-11 18:28:15,519:app:INFO:user 2 deleted ticket
2020-09-11 18:28:20,604:app:INFO:manager 2  accessed tickets list
2020-09-11 18:28:20,635:app:INFO:manager 2  accessed tickets list
2020-09-11 18:29:24,931:app:INFO:manager 2  accessed tickets list
2020-09-11 18:29:25,004:app:INFO:manager 2 verified ticket 4
2020-09-11 18:29:25,020:app:INFO:manager 2  accessed tickets list
2020-09-11 18:29:25,035:app:INFO:manager 2  accessed tickets list
2020-09-11 18:29:29,669:app:INFO:manager 2  accessed tickets list
2020-09-11 18:29:31,011:app:WARNING:Invalid input params: {'buyer_email': ['Not a valid email address.']}
2020-09-11 18:29:31,070:app:INFO:manager 2  accessed tickets list
2020-09-11 18:29:31,111:app:INFO:manager 2  accessed tickets list
2020-09-11 18:29:36,634:app:INFO:user 1 deleted ticket
2020-09-11 18:29:36,666:app:INFO:user 2 deleted ticket
2020-09-11 18:29:41,820:app:INFO:manager 2  accessed tickets list
2020-09-11 18:29:41,851:app:INFO:manager 2  accessed tickets list
2020-09-11 18:33:44,484:app:INFO:manager 2  accessed tickets list
2020-09-11 18:33:44,515:app:INFO:manager 2 verified ticket 4
2020-09-11 18:33:44,531:app:INFO:manager 2  accessed tickets list
2020-09-11 18:33:44,538:app:INFO:manager 2  accessed tickets list
2020-09-11 18:33:49,041:app:INFO:manager 2  accessed tickets list
2020-09-11 18:33:49,668:app:WARNING:Invalid input params: {'buyer_email': ['Not a valid email address.']}
2020-09-11 18:33:49,699:app:INFO:manager 2  accessed tickets list
2020-09-11 18:33:49,721:app:INFO:manager 2  accessed tickets list
2020-09-11 18:33:53,959:app:INFO:user 1 deleted ticket
2020-09-11 18:33:53,992:app:INFO:user 2 deleted ticket
2020-09-11 18:33:56,691:app:INFO:manager 2  accessed tickets list
2020-09-11 18:33:56,700:app:INFO:manager 2  accessed tickets list
2020-09-12 23:46:20,399:app:INFO:manager 2  accessed tickets list
2020-09-12 23:46:24,749:app:INFO:manager 2  accessed tickets list
2020-09-12 23:46:35,584:app:INFO:manager 2  accessed tickets list
2020-09-12 23:59:26,818:app:INFO:manager 2  accessed tickets list
2020-09-12 23:59:31,503:app:INFO:manager 2  accessed tickets list
2020-09-12 23:59:42,528:app:INFO:manager 2  accessed tickets list
2020-09-13 00:27:33,900:app:INFO:manager 2  accessed tickets list
2020-09-13 00:27:38,411:app:INFO:manager 2  accessed tickets list
2020-09-13 00:27:45,005:app:INFO:manager 2  accessed tickets list
2020-09-12 22:35:56,930:app:INFO:thread 13452 begins the proccess
2020-09-12 23:25:53,657:app:INFO:thread 3212 begins the proccess

2020-09-13 02:02:44,821:app:INFO:manager 2  accessed tickets list
2020-09-13 02:02:51,652:app:INFO:manager 2  accessed tickets list
2020-09-13 02:03:04,230:app:INFO:manager 2  accessed tickets list
2020-09-13 02:04:30,361:app:INFO:manager 2  accessed tickets list
2020-09-13 02:04:30,411:app:INFO:manager 2 verified ticket 4
2020-09-13 02:04:30,420:app:INFO:manager 2  accessed tickets list
2020-09-13 02:04:30,450:app:INFO:manager 2  accessed tickets list
2020-09-13 02:04:36,395:app:INFO:manager 2  accessed tickets list
2020-09-13 02:04:37,623:app:WARNING:Invalid input params: {'buyer_email': ['Not a valid email address.']}
2020-09-13 02:04:37,666:app:INFO:manager 2  accessed tickets list
2020-09-13 02:04:37,720:app:INFO:manager 2  accessed tickets list
2020-09-13 02:04:43,940:app:INFO:user 1 deleted ticket
2020-09-13 02:04:43,961:app:INFO:user 2 deleted ticket
2020-09-13 02:04:50,150:app:INFO:manager 2  accessed tickets list
2020-09-13 02:04:50,196:app:INFO:manager 2  accessed tickets list
2020-09-14 01:25:46,247:app:INFO:manager 2  accessed tickets list
2020-09-14 01:25:46,287:app:INFO:manager 2 verified ticket 4
2020-09-14 01:25:46,317:app:INFO:manager 2  accessed tickets list
2020-09-14 01:25:46,342:app:INFO:manager 2  accessed tickets list
2020-09-14 01:25:50,892:app:INFO:manager 2  accessed tickets list
2020-09-14 01:25:52,068:app:WARNING:Invalid input params: {'buyer_email': ['Not a valid email address.']}
2020-09-14 01:25:52,131:app:INFO:manager 2  accessed tickets list
2020-09-14 01:25:52,162:app:INFO:manager 2  accessed tickets list
2020-09-14 01:25:57,307:app:INFO:user 1 deleted ticket
2020-09-14 01:25:57,348:app:INFO:user 2 deleted ticket
2020-09-14 01:26:02,648:app:INFO:manager 2  accessed tickets list
2020-09-14 01:26:02,678:app:INFO:manager 2  accessed tickets list
